### ISSUE TITLE
Setting to choose lenght of pause

### ISSUE THREAD

**Issue by forteller** [tijn/pause-night-light#3]
This is really great! Thanks! But it would be useful for even more people if there was a setting that let you choose for how long the pause should last.

Maybe you could even let each user add more "pause buttons", so that you could have different lengths for different uses? Like for example have both a "Pause for 10 seconds" and a "Pause for 3 hours". But this is less important :)

**Comment by tijn** [comment]
Well, you're not wrong, obviously that could be useful, but I have some remarks:

- Can you show or describe a good way to configure the time **in a simple way**. I am hesitant to make the UI more complex than it needs to be.
- Do you yourself have any specific request for certain time spans? Do you have a specific need or use case in mind?

**Comment by tijn** [comment]
Closing this because of lack of conversation. Feel free to reopen if there are new insights to be shared.

**Comment by forteller** [comment]
Hey, @tijn! I really appreciate your fast reply, and I'm sorry I didn't get around to answer you any sooner! Here's my proposal for a settings screen. The slides should obviously be at different places along the scale, but I couldn't figure out how to do that in the software I used.

![screenshot from 2017-11-11 01-27-15](https://user-images.githubusercontent.com/343561/32683967-1bf5c25a-c677-11e7-920c-4cdcca366f58.png)

**Comment by tijn** [comment]
Right, but how would you open the settings menu? Where would you place the settings button?

And, even more important, do you @forteller have any specific request for certain time spans? Do you have a specific need or use case in mind?

**Comment by forteller** [comment]
Extensions has a built in system for including settings. The button is available from https://extensions.gnome.org/local/ and from Gnome Tweaks, if you have that installed.

I'd love to have 1 hour and 2 hours as time spans to select. That way I can start on a tv episode (1 hour) or movie (2 hours) right before midnight without the night light turning on in the middle of watching :)

**Comment by forteller** [comment]
I was still hoping you would implement this at some point. But I see now that you've closed this issue. So, should I just uninstall then, instead of having it installed, but turned off, waiting for an update?

This is your project, you of course do what you want with it :)

**Comment by tijn** [comment]
Yes, that's correct. Your proposal is completely out of scope for this project.

I made you a small script that I think will work better for your use case:

```sh
#!/bin/sh
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false
sleep 5
mplayer $@ 
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
```

Save this as `/usr/local/bin/play-tv-episode` or whatever name you would like it to have and `chmod +x` it.

Then run it like this:

```bash session
play-tv-episode [OPTION]... FILENAME(S)
```

This will play your video with night light off, and when it's done, it'll enable night light again.
You can easily substitute mplayer with vlc or whichever video-player you prefer and set some flags if you wish to do so. It's also possible to register this script as an alternative video player for video files in Gnome if you don't like using the terminal.

**Comment by forteller** [comment]
Oh, wow. That's awesome! Thanks! :)
