### ISSUE TITLE
use shorter menu item: ‘Disable briefly’

### ISSUE THREAD

**Issue by wbolster** [tijn/pause-night-light#7]
i would suggest to remove the duration from the menu item text. something like ‘Disable briefly’ is short and descriptive enough. a short label avoids wide menus, which happens when using a localization that uses a significantly longer string, see e.g. #5.

**Comment by tijn** [comment]
Yeah, I agree, that sounds better. I'll change it to "disable briefly". 

Heb jij heel toevallig nog een goede Nederlandse vertaling? ("Effe uitzetten" :stuck_out_tongue_closed_eyes:) Ik gebruik altijd Engels op de computer dus ik heb niet zo een twee drie de gebruikelijke woorden paraat, maar jij misschien wel! (?)

**Comment by tijn** [comment]
Oh.. looking at your PR, that should obviously be "kort uitschakelen". Thanks! :smile:

**Comment by wbolster** [comment]
"kort uitschakelen" inderdaad. altijd infinitief, bij voorkeur aan het einde. (voormalig coördinator gnome-nl hier.)

ik wissel tussen gnome in het nederlands, engels (uk-variant) en zweeds. engels is zo saai... en met andere instellingen vind je interessante bugs. :)

**Comment by tijn** [comment]
TODO:

- [x] Προσωρινή απενεργοποίηση
- [x] Kurz deaktivieren (without umlauts @tijn!)
- [x] tag new version
- [x] make zip, upload, ... wait

**Comment by wbolster** [comment]
good busy 😉

**Comment by wbolster** [comment]
any chance you can upload a new version? i still see ugly strings in my menu. :)

**Comment by tijn** [comment]
@wbolster yes, I have postponed this for too long already! I just uploaded a new version, I hope it'll get through review soon.

**Comment by wbolster** [comment]
awesome, thanks!
